	<form class="form create account form-create-account" data-mage-init='{"contactForm":{}}' action="http://2vikki.dz/customer/account/createpost/" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off" novalidate="novalidate">
		<input name="form_key" type="hidden" value="8ikjpudGI5fRassB">    <fieldset class="fieldset create info">
			<legend class="legend"><span>Personal Information</span></legend><br>
			<input type="hidden" name="success_url" value="">
			<input type="hidden" name="error_url" value="">

			<div class="field field-name-firstname required">
				<label class="label" for="firstname"><span>First Name</span></label>
				<div class="control">
					<input type="text" id="firstname" name="firstname" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
				</div>
			</div>
			<div class="field field-name-lastname required">
				<label class="label" for="lastname"><span>Last Name</span></label>
				<div class="control">
					<input type="text" id="lastname" name="lastname" value="" title="Last Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
				</div>
			</div>

			<div class="field choice newsletter">
				<input type="checkbox" name="is_subscribed" title="Sign Up for Newsletter" value="1" id="is_subscribed" class="checkbox">
				<label for="is_subscribed" class="label"><span>Sign Up for Newsletter</span></label>
			</div>



		</fieldset>
		<fieldset class="fieldset create account" data-hasrequired="* Required Fields">
			<legend class="legend"><span>Sign-in Information</span></legend><br>
			<div class="field required">
				<label for="email_address" class="label"><span>Email</span></label>
				<div class="control">
					<input type="email" name="email" autocomplete="email" id="email_address" value="" title="Email" class="input-text" data-validate="{required:true, 'validate-email':true}" aria-required="true">
				</div>
			</div>
			<div class="field password required">
				<label for="password" class="label"><span>Password</span></label>
				<div class="control">
					<input type="password" name="password" id="password" title="Password" class="input-text" data-password-min-length="8" data-password-min-character-sets="3" data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off" aria-required="true">
					<div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
						<div id="password-strength-meter" class="password-strength-meter">
							Password Strength:
							<span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            No Password                        </span>
						</div>
					</div>
				</div>

			</div>
			<div class="field confirmation required">
				<label for="password-confirmation" class="label"><span>Confirm Password</span></label>
				<div class="control">
					<input type="password" name="password_confirmation" title="Confirm Password" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off" aria-required="true">
				</div>
			</div>
		</fieldset>
		<div class="actions-toolbar">
			<div class="primary">
				<button type="submit" class="action submit primary" title="Create an Account"><span>Create an Account</span></button>
			</div>
			<div class="secondary">
				<a class="action back" href="http://2vikki.dz/customer/account/login/referer/aHR0cDovLzJ2aWtraS5kei9jdXN0b21lci9hY2NvdW50L2NyZWF0ZS8%2C/"><span>Back</span></a>
			</div>
		</div>
	</form>
	<script>
        /*require([
            'jquery',
            'mage/mage'
        ], function($){

            var dataForm = $('#form-validate');
            var ignore = null;

            dataForm.mage('validation', {
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            }).find('input:text').attr('autocomplete', 'off');

        });*/
	</script>
