<div class="uk-container uk-margin-large">
    <form class="form create account form-create-account contact-form" data-mage-init='{"contactForm":{"submitButton":"#submit-contract-form"}}' action="#" method="post" id="form-validate" autocomplete="off" novalidate="novalidate">
		<input name="form_key" type="hidden" value="8ikjpudGI5fRassB">    <fieldset class="fieldset create info">
			<input type="hidden" name="success_url" value="">
			<input type="hidden" name="error_url" value="">

			<div class="field field-name-firstname required">
				<label class="label" for="firstname"><span><?= __('Your Name') ?></span></label>
				<div class="control">
					<input type="text" id="firstname" name="firstname" value="" title="<?= __('Your Name') ?>" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
				</div>
			</div>
            <div class="field field-name-firstname required">
                <label class="label" for="email"><span><?= __('Your E-mail') ?></span></label>
                <div class="control">
                    <input type="text" id="email" name="email" value="" title="<?= __('Your E-mail') ?>" class="input-text required-entry" data-validate="{required:true,email:true}" autocomplete="off" aria-required="true">
                </div>
            </div>
            <div class="field field-name-firstname required">
                <label class="label" for="subject"><span><?= __('Subject') ?></span></label>
                <div class="control">
                    <input type="text" id="subject" name="subject" value="" title="<?= __('Subject') ?>" class="input-text required-entry" data-validate="{required:true,maxlength:100,minlength:5}" autocomplete="off" aria-required="true">
                </div>
            </div>
            <div class="field field-name-firstname required">
                <label class="label" for="text"><span><?= __('E-mail Text') ?></span></label>
                <div class="control">
                    <textarea id="text" name="text" title="<?= __('E-mail Text') ?>" class="input-text required-entry" data-validate="{required:true,maxlength:300,minlength:20}" autocomplete="off" aria-required="true"></textarea>
                </div>
            </div>
		</fieldset>
        <div class="uk-text-center uk-margin-bottom contact-form-recaptcha">
		    <?= $block->getChildHtml() ?>
        </div>
		<div class="uk-text-center">
            <button type="submit" class="action submit primary" id="submit-contract-form" title="<?= __('Submit E-mail') ?>"><span><?= __('Submit E-mail') ?></span></button>
		</div>
	</form>
	<script>
        /*require([
            'jquery',
            'mage/mage'
        ], function($){

            var dataForm = $('#form-validate');
            var ignore = null;

            dataForm.mage('validation', {
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            }).find('input:text').attr('autocomplete', 'off');

        });*/
	</script>
</div>
