<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<div class="uk-width-medium-1-2 uk-row-first">
    <div class="uk-panel">
        <ul class="uk-subnav uk-subnav-line">
            <?= /* @escapeNotVerified */ $_menu ?>
            <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
        </ul>
    </div>
</div>


